package com.ws.tianque;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-12-13T09:36:26.926+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://service.webService.issue.plugin.tianque.com/", name = "WbsIssue")
@XmlSeeAlso({ObjectFactory.class})
public interface WbsIssue {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchClearIssuesCount", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.SearchClearIssuesCount")
    @WebMethod
    @ResponseWrapper(localName = "searchClearIssuesCountResponse", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.SearchClearIssuesCountResponse")
    public IssueCount searchClearIssuesCount(
            @WebParam(name = "arg0", targetNamespace = "")
                    javax.xml.datatype.XMLGregorianCalendar arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addIssueNew", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.AddIssueNew")
    @WebMethod
    @ResponseWrapper(localName = "addIssueNewResponse", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.AddIssueNewResponse")
    public String addIssueNew(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @RequestWrapper(localName = "updateWbsIssue", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.UpdateWbsIssue")
    @WebMethod
    @ResponseWrapper(localName = "updateWbsIssueResponse", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.UpdateWbsIssueResponse")
    public void updateWbsIssue(
            @WebParam(name = "arg0", targetNamespace = "")
                    boolean arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.util.List<String> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getGridMenberStat", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.GetGridMenberStat")
    @WebMethod
    @ResponseWrapper(localName = "getGridMenberStatResponse", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.GetGridMenberStatResponse")
    public String getGridMenberStat(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    Integer arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    Integer arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "viewIssueInformation", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.ViewIssueInformation")
    @WebMethod
    @ResponseWrapper(localName = "viewIssueInformationResponse", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.ViewIssueInformationResponse")
    public String viewIssueInformation(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "viewIssueDetail", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.ViewIssueDetail")
    @WebMethod
    @ResponseWrapper(localName = "viewIssueDetailResponse", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.ViewIssueDetailResponse")
    public IssueDetailVo viewIssueDetail(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addIssueEvaluateVo", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.AddIssueEvaluateVo")
    @WebMethod
    @ResponseWrapper(localName = "addIssueEvaluateVoResponse", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.AddIssueEvaluateVoResponse")
    public String addIssueEvaluateVo(
            @WebParam(name = "arg0", targetNamespace = "")
                    IssueEvaluateVo arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWbsIssues", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.GetWbsIssues")
    @WebMethod
    @ResponseWrapper(localName = "getWbsIssuesResponse", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.GetWbsIssuesResponse")
    public java.util.List<com.ws.tianque.WbsIssueTemp> getWbsIssues(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addPetitionIssue", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.AddPetitionIssue")
    @WebMethod
    @ResponseWrapper(localName = "addPetitionIssueResponse", targetNamespace = "http://service.webService.issue.plugin.tianque.com/", className = "com.ws.tianque.AddPetitionIssueResponse")
    public IssueViewObject addPetitionIssue(
            @WebParam(name = "arg0", targetNamespace = "")
                    PetitionIssueVo arg0
    );
}
